# denzp -> diepes
# checkout@v1 -> v3
name: Publish the cargo-container-tools
on:
  push:
    tags:
      - cargo-container-tools-*

jobs:
  publish-requested-tag:
    name: Publish diepes/cargo-container-tools
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Print docker info
        run: docker info

      - name: Login to Docker Hub Registry
        run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      #- name: Installing buildx
      #  run: .ci/install-buildx.sh

      - name: Build and push the image
        env:
          TAG: ${{ github.ref }}
        run: >-
          docker buildx build
          --push -f cargo-container-tools/Cargo.toml .
          --tag diepes/cargo-container-tools:${TAG#"refs/tags/cargo-container-tools-"}
          --cache-from type=registry,ref=diepes/cargo-container-tools:cache
